#!/bin/bash
#
# Token 共享流程演示
# 展示如何在多台机器间共享 Token
#

echo "╔════════════════════════════════════════════════════════════╗"
echo "║     OpenClaw 联邦部署 - Token 共享流程演示                ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# 模拟主节点部署
echo "═══════════════════════════════════════════════════════════"
echo "【步骤 1】在主节点 (VPS) 上部署"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "$ ./deploy-federation.sh master"
echo ""
echo "... 部署中 ..."
echo ""
echo "[OK] Gateway 配置完成"
echo "[OK] 监听地址: 100.64.0.1:18789"
echo "[OK] Gateway 启动成功"
echo ""
echo "═════���═════════════════════════════════════════════════════"
echo "【生成的 Token】"
echo "═══════════════════════════════════════════════════════════"
echo ""

# 生成示例 Token
TOKEN=$(openssl rand -hex 32)
echo "Token: $TOKEN"
echo ""
echo "保存位置: /root/.openclaw/.federation-token"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "【步骤 2】Token 共享方式（选择一种）"
echo "═══════════════════════════════════════════════════════════"
echo ""

echo "方式 1: 复制粘贴（最简单）"
echo "───────────────────────────────────────────────────────────"
echo "  1. 复制上面的 Token"
echo "  2. 在工作节点上运行:"
echo ""
echo "     ./deploy-federation.sh worker \\"
echo "       --master-ip 100.64.0.1 \\"
echo "       --node-name home-server \\"
echo "       --token \"$TOKEN\""
echo ""

echo "方式 2: SSH 传输 Token 文件"
echo "───────────────────────────────────────────────────────────"
echo "  在主节点执行:"
echo ""
echo "     scp /root/.openclaw/.federation-token \\"
echo "       user@home-server:/root/.openclaw/.federation-token"
echo ""
echo "  然后在工作节点上运行:"
echo ""
echo "     ./deploy-federation.sh worker \\"
echo "       --master-ip 100.64.0.1 \\"
echo "       --node-name home-server"
echo ""

echo "方式 3: 直接 SSH 写入（无需复制文件）"
echo "───────────────────────────────────────────────────────────"
echo "  在主节点执行:"
echo ""
echo "     ssh user@home-server \\"
echo "       \"mkdir -p /root/.openclaw && \\"
echo "        echo '$TOKEN' > /root/.openclaw/.federation-token\""
echo ""
echo "  然后在工作节点上运行:"
echo ""
echo "     ./deploy-federation.sh worker \\"
echo "       --master-ip 100.64.0.1 \\"
echo "       --node-name home-server"
echo ""

echo "方式 4: 环境变量"
echo "───────────────────────────────────────────────────────────"
echo "  在工作节点上:"
echo ""
echo "     export FEDERATION_TOKEN=\"$TOKEN\""
echo ""
echo "     ./deploy-federation.sh worker \\"
echo "       --master-ip 100.64.0.1 \\"
echo "       --node-name home-server"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "【步骤 3】验证 Token 一致性"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "部署完成后，可以在所有节点上验证 Token:"
echo ""
echo "  主节点:  cat /root/.openclaw/.federation-token"
echo "  工作节点: cat /root/.openclaw/.federation-token"
echo ""
echo "两个文件内容应该完全相同！"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "【完整部署示例】"
echo "═══════════════════════════════════════════════════════════"
echo ""

echo "假设有 3 台机器:"
echo "  - VPS (主节点): 100.64.0.1"
echo "  - 家庭服务器:   100.64.0.2"
echo "  - Mac:          100.64.0.3"
echo ""

echo "【VPS 上执行】"
echo "─────────────"
echo "$ ./deploy-federation.sh master"
echo "..."
echo "Token: $TOKEN"
echo ""

echo "【家庭服务器上执行】"
echo "───────────────────"
echo "$ ./deploy-federation.sh worker \\"
echo "    --master-ip 100.64.0.1 \\"
echo "    --node-name home-server \\"
echo "    --token \"$TOKEN\" \\"
echo "    --skills \"docker k8s\""
echo ""

echo "【Mac 上执行】"
echo "─────────────"
echo "$ ./deploy-federation.sh worker \\"
echo "    --master-ip 100.64.0.1 \\"
echo "    --node-name mac-pc \\"
echo "    --token \"$TOKEN\" \\"
echo "    --skills \"apple-notes\""
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "【验证部署】"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "在主节点 (VPS) 上执行:"
echo ""
echo "  $ openclaw nodes list"
echo "  ID    Name         URL                      Status"
echo "  ───────────────────────────────────────────────────"
echo "  n-xxx home-server  ws://100.64.0.2:18789    connected"
echo "  n-yyy mac-pc       ws://100.64.0.3:18789    connected"
echo ""
echo "  $ openclaw nodes invoke home-server -- docker ps"
echo "  $ openclaw nodes invoke mac-pc -- uname -a"
echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║                     部署成功！                            ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
